import { isSupabaseConfigured, supabaseRest } from "./supabase";
export { isSupabaseConfigured };
export interface EventRecord { id:string; slug:string; title:string; date:string|null; description:string; cover_image:string|null; cover_image_drive_id?:string|null; drive_folder_id:string; photos_drive_folder_id?:string|null; photos_drive_folder_id_2?:string|null; videos_drive_folder_id?:string|null; videos_drive_folder_id_2?:string|null; sort_order:number; is_active:boolean; photos_enabled:boolean; videos_enabled:boolean; slideshow_enabled:boolean; qr_enabled:boolean; venue_name:string|null; venue_address:string|null; maps_url:string|null; created_at?:string; updated_at?:string; }
export interface GuestbookMessage { id:string; name:string; message:string; approved:boolean; created_at:string; featured?:boolean; }
const FALLBACK_FOLDER=import.meta.env.VITE_GOOGLE_DRIVE_FOLDER_ID||"1G5IZFca5VNZdK3zbDLP977zIWvqerZcv";
const FALLBACK:EventRecord[]=[["engagement","Engagement"],["pre-wedding","Pre-Wedding Photoshoot"],["lagnapathrika","Lagnapathrika"],["mangala-snanam","Mangala Snanam"],["haldi","Haldi"],["prathanam","Prathanam"],["upanayanam","Upanayanam"],["marriage","Marriage"],["satyanarayana-vratham","Sathya Narayana Vratham"]].map(([slug,title],index)=>({id:slug,slug,title,date:null,description:`${title} memories of Hareesh & Prasanna.`,cover_image:null,cover_image_drive_id:null,drive_folder_id:FALLBACK_FOLDER,photos_drive_folder_id:FALLBACK_FOLDER,photos_drive_folder_id_2:null,videos_drive_folder_id:FALLBACK_FOLDER,videos_drive_folder_id_2:null,sort_order:index,is_active:true,photos_enabled:true,videos_enabled:true,slideshow_enabled:true,qr_enabled:true,venue_name:null,venue_address:null,maps_url:null}));
let cache:{at:number;data:EventRecord[]}|null=null;
export async function getEvents(force=false):Promise<EventRecord[]>{if(!force&&cache&&Date.now()-cache.at<60_000)return cache.data;if(!isSupabaseConfigured)return FALLBACK;try{const data=await supabaseRest<EventRecord[]>("events_public",{query:"select=*&order=sort_order.asc"});cache={at:Date.now(),data};return data;}catch{return FALLBACK;}}
export async function getEvent(slug:string){return (await getEvents()).find(item=>item.slug===slug)||null;}
export async function submitGuestbook(name:string,message:string,website=""){if(!isSupabaseConfigured)return null;const response=await fetch("/api/guestbook",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,message,website})});let data:{ok?:boolean;error?:string}={};try{data=await response.json();}catch{}if(!response.ok||!data.ok)throw new Error(data.error||"Unable to save your message right now.");return null;}
export async function getApprovedGuestbook(limit=30):Promise<GuestbookMessage[]>{if(!isSupabaseConfigured)return [];const response=await fetch(`/api/guestbook?limit=${Math.min(Math.max(limit,1),100)}`,{cache:"no-store",headers:{Accept:"application/json"}});if(!response.ok)throw new Error("Unable to load guestbook.");return response.json();}
export async function getPendingGuestbook(token:string):Promise<GuestbookMessage[]>{if(!token)throw new Error("Admin session is missing.");return supabaseRest<GuestbookMessage[]>("guestbook",{token,query:"select=id,name,message,approved,moderation_status,featured,created_at&moderation_status=eq.pending&order=created_at.desc"});}
export async function setGuestbookApproval(token:string,id:string,approved:boolean){if(!token)throw new Error("Admin session is missing.");if(!id)throw new Error("Guestbook message ID is missing.");return supabaseRest("guestbook",{method:"PATCH",token,query:`id=eq.${encodeURIComponent(id)}`,body:{approved},prefer:"return=representation"});}
export async function deleteGuestbookMessage(token:string,id:string){if(!token)throw new Error("Admin session is missing.");if(!id)throw new Error("Guestbook message ID is missing.");return supabaseRest("guestbook",{method:"DELETE",token,query:`id=eq.${encodeURIComponent(id)}`});}
export async function writeAdminAudit(token:string,action:any,targetId?:string|null,details:Record<string,unknown>={}){if(!token)throw new Error("Admin session is missing.");return supabaseRest("admin_audit_logs",{method:"POST",token,body:{action,target_id:targetId||null,details},prefer:"return=minimal"});}

export interface HomepageSectionRecord{key:string;label:string;enabled:boolean;sort_order:number;updated_at?:string;}
export async function getHomepageSections(){if(!isSupabaseConfigured)return [];return supabaseRest<HomepageSectionRecord[]>("homepage_sections",{query:"select=*&order=sort_order.asc"});}
export async function getPublicNotifications(limit=10){if(!isSupabaseConfigured)return [];return supabaseRest<any[]>("notifications_public",{query:`limit=${Math.min(Math.max(limit,1),50)}`});}
export async function getSiteSettings(){if(!isSupabaseConfigured)return {wedding:{},theme:{},siteControl:{}};const rows=await supabaseRest<{key:string;value:any}[]>("site_settings_public",{query:"select=key,value"});return Object.fromEntries(rows.map(row=>[row.key,row.value]));}
