import type { LucideIcon } from "lucide-react";
import { Activity, BarChart3, Bell, BookOpen, Boxes, CalendarDays, FileArchive, FileClock, FileImage, Gauge, Globe2, Heart, HelpCircle, LayoutDashboard, Link2, MapPin, Palette, QrCode, Rocket, Settings2, ShieldCheck, Sparkles, Trash2, UserCog, Megaphone, Users, ClipboardCheck } from "lucide-react";

export type PermissionAction = "view" | "create" | "edit" | "delete" | "publish" | "manage";
export type AdminRole = "administrator" | "editor" | "moderator" | "view_only" | "custom";
export interface AdminModule { id:string; number:number; label:string; description:string; icon:LucideIcon; group:"wedding"|"insights"|"management"|"system"; actions:PermissionAction[]; status?:"active"|"planned"; children:{id:string;label:string;description?:string}[]; }
const children=(items:string[])=>items.map(id=>({id,label:id.replaceAll("-"," ")}));
const all:[PermissionAction,PermissionAction,PermissionAction,PermissionAction,PermissionAction,PermissionAction]=["view","create","edit","delete","publish","manage"];
export const ADMIN_MODULES:AdminModule[]=[
{id:"dashboard",number:1,label:"Dashboard",description:"Website status, pending actions, quick links, countdown, recent activity and system health.",icon:LayoutDashboard,group:"wedding",actions:["view","manage"],children:children(["status","notifications-actions","analytics-summary","quick-links","recent-activity","system-health"])},
{id:"website",number:3,label:"Website",description:"Home page section manager and every editable public website section.",icon:Globe2,group:"wedding",actions:all,children:children(["section-manager","intro","navigation","home-hero","couple","story","gallery","events","rsvp","guestbook","footer"])},
{id:"styling",number:4,label:"Styling",description:"Theme, colours, typography, animations and responsive layout controls.",icon:Palette,group:"wedding",actions:["view","edit","publish","manage"],children:children(["theme","colours","typography","animations","responsive"])},
{id:"loading-intro",number:4,label:"Loading & Intro",description:"Loading screen and intro behaviour from the specification.",icon:Sparkles,group:"wedding",actions:["view","edit","publish","manage"],children:children(["loading-screen","loading-text","loading-logo","loading-animation","blink-heart","loading-duration","intro-video","autoplay","mute","skip-button","fullscreen","mobile-landscape","preview"])},
{id:"alerts",number:5,label:"Alerts",description:"Maintenance and announcement scheduling and page targeting.",icon:Megaphone,group:"wedding",actions:["view","create","edit","delete","publish","manage"],children:children(["maintenance-status","maintenance-message","maintenance-apply-to","announcement-status","announcement-message","announcement-apply-to"])},
{id:"notifications",number:6,label:"Notification / Actions",description:"Notification inbox plus pending, completed and failed administrative actions.",icon:Bell,group:"insights",actions:["view","create","edit","delete","manage"],children:children(["notification-list","pending-actions","completed-actions","failed-actions"])},
{id:"analytics",number:7,label:"Analytics",description:"Website, visitor, page, RSVP, gallery and export analytics.",icon:BarChart3,group:"insights",actions:["view","manage"],children:children(["overview","visitors","pages","rsvp","gallery","export"])},
{id:"events",number:8,label:"Events / Story Memory",description:"Event list and detailed event information, scheduling, locations and protected access.",icon:CalendarDays,group:"wedding",actions:all,children:children(["event-list","event-details","event-information","schedule","location","gallery","videos","visibility","security"])},
{id:"rsvp",number:9,label:"RSVP",description:"RSVP overview, guest management and configurable RSVP form fields.",icon:ClipboardCheck,group:"wedding",actions:all,children:children(["overview","guest-list","search","filter","add-guest","edit-guest","delete-guest","import","export","form-fields","attendance","plus-one","meal-preference","dietary-requirements","additional-message"])},
{id:"guestbook",number:10,label:"Guestbook",description:"Guestbook moderation, approval, rejection, spam handling and settings.",icon:BookOpen,group:"wedding",actions:["view","edit","delete","manage"],children:children(["messages","pending","approved","rejected","spam","settings","moderation"])},
{id:"social",number:11,label:"Social & Contact",description:"Social links and contact information used by the public wedding website.",icon:Link2,group:"wedding",actions:["view","edit","publish","manage"],children:children(["social-links","instagram","youtube","facebook","whatsapp","contact-information","phone","email"])},
{id:"media",number:12,label:"Media",description:"Media source, gallery links, photo/video management, optimization, privacy and guest uploads.",icon:FileImage,group:"wedding",actions:all,children:children(["media-source","gallery-qr-links","photo-video-listing","pagination","image-performance","media-delivery","guest-uploads","media-privacy","private-media-delivery"])},
{id:"interactions",number:13,label:"Interactions",description:"Event unlock, sessions, security, guestbook, analytics, favorites, QR and guest photo upload controls.",icon:Heart,group:"wedding",actions:["view","edit","delete","manage"],children:children(["event-unlock","unlock-session","event-code-storage","unlock-protection","guestbook-interaction","analytics-interaction","favorites","qr-interaction","guest-photo-upload"])},
{id:"access",number:14,label:"Access Management",description:"Users, roles and permissions defined by the specification.",icon:Users,group:"management",actions:all,children:children(["users","user-list","add-user","edit-user","disable-user","delete-user","reset-password","roles","permissions","website","styling","rsvp","guestbook","media","analytics","publishing","administration","security"])},
{id:"administration",number:15,label:"Administration",description:"Website information and administrator dashboard preferences.",icon:UserCog,group:"management",actions:all,children:children(["website-details","website-name","website-url","wedding-date","time-zone","language","date-format","admin-preferences","default-dashboard","default-theme","notification-preferences"])},
{id:"security",number:16,label:"Security",description:"Account security, security alerts and event security center.",icon:ShieldCheck,group:"management",actions:["view","edit","manage"],children:children(["account-security","change-password","two-factor","active-sessions","login-history","force-logout","security-alerts","failed-login-alert","new-login-alert","password-change-alert","security-email","security-center","event-security"])},
{id:"audit",number:17,label:"Audit Logs",description:"Searchable activity records with user, action, target, result and export details.",icon:FileClock,group:"management",actions:["view","manage"],children:children(["activity-logs","all-activity","filter-user","filter-action","filter-date","search","details","export"])},
{id:"publishing",number:18,label:"Publishing",description:"Publishing status, preview, scheduled publishing, unpublish and version history.",icon:Rocket,group:"system",actions:all,children:children(["publishing-status","preview","publish-now","schedule-publish","unpublish","cancel-scheduled-publish","version-history","view-version","compare-version","restore-version"])},
{id:"diagnostics",number:19,label:"Testing & Diagnostics",description:"Website tests, performance tests, automated tests, cache, code splitting and diagnostic logs.",icon:Activity,group:"system",actions:["view","manage"],children:children(["website-test","broken-links","missing-images","missing-alt-text","form-validation","rsvp-test","guestbook-test","performance","page-load","gallery-load","lazy-loading","thumbnail-optimization","video-loading","drive-pagination","api-response","cache-status","service-worker","mobile-performance","desktop-performance","automated-testing","run-all-tests","unit-tests","api-tests","authentication-tests","rsvp-tests","guestbook-tests","gallery-tests","guest-upload-tests","test-results","application-cache","clear-cache","update-service-worker","application-loading","code-splitting","admin-route-loading","gallery-route-loading","video-route-loading","lazy-loaded-components","diagnostics","error-logs","warning-logs","api-errors","integration-errors","run-diagnostics"])},
{id:"integrations",number:20,label:"Integrations",description:"Supabase, Google Drive, GitHub, Vercel, environment variables and API service health.",icon:Boxes,group:"system",actions:all,children:children(["database","supabase","storage","google-drive","source-code","github","deployment","vercel","environment-configuration","environment-variables","api-services","event-unlock-api","guestbook-api","analytics-api","google-drive-api","guest-upload-api","other-integrations"])},
{id:"system",number:21,label:"System",description:"System information and service status.",icon:Gauge,group:"system",actions:["view","manage"],children:children(["system-information","application-version","database-version","server-information","environment","time-zone","storage-usage","system-services","website-service","database-service","storage-service","email-service","api-service","cache-service"])},
{id:"backup",number:22,label:"Backup & Restore",description:"Full, website, media and database backups, history, export, import and restore.",icon:FileArchive,group:"system",actions:["view","create","delete","manage"],children:children(["backup","full-backup","website-content-backup","media-backup","database-backup","backup-history","export","import","restore"])},
{id:"settings",number:23,label:"Settings",description:"General, wedding, date/time, language, notification, website and advanced settings.",icon:Settings2,group:"system",actions:["view","edit","manage"],children:children(["general","wedding","date-time","language","notifications","website","advanced"])},
{id:"trash",number:24,label:"Trash & Recovery",description:"Recover or permanently delete soft-deleted records.",icon:Trash2,group:"system",actions:["view","delete","manage"],children:children(["all","events","media","guestbook","content","restore","permanent-delete"])},
{id:"help",number:25,label:"Help & Support",description:"Documentation, support actions and application information.",icon:HelpCircle,group:"system",actions:["view"],children:children(["help","documentation","support","support-actions","about","application-information"])}
];
export const ADMIN_ROLES:Record<AdminRole,{label:string;description:string;permissions:Record<string,PermissionAction[]>}>={
 administrator:{label:"Administrator",description:"Full administrative control.",permissions:Object.fromEntries(ADMIN_MODULES.map(m=>[m.id,m.actions]))},
 editor:{label:"Editor",description:"Manage wedding content without security administration.",permissions:Object.fromEntries(ADMIN_MODULES.filter(m=>!["access","administration","security","audit","integrations","system","backup"].includes(m.id)).map(m=>[m.id,m.actions.filter(a=>["view","create","edit","publish"].includes(a))]))},
 moderator:{label:"Moderator",description:"Moderate guest-facing interactions.",permissions:{guestbook:["view","edit","delete","manage"],interactions:["view","delete","manage"],notifications:["view","manage"],rsvp:["view","edit"],dashboard:["view"]}},
 view_only:{label:"View Only",description:"Read-only access.",permissions:Object.fromEntries(ADMIN_MODULES.map(m=>[m.id,["view"]]))},
 custom:{label:"Custom Role",description:"Explicitly assigned permissions.",permissions:{}}
};
export const GROUP_LABELS={wedding:"WEDDING",insights:"INSIGHT",management:"MANAGEMENT",system:"SYSTEM"} as const;
