import type { LucideIcon } from "lucide-react";
import { Activity, BarChart3, Bell, BookOpen, Boxes, CalendarDays, FileArchive, FileClock, FileImage, Gauge, Globe2, Heart, HelpCircle, LayoutDashboard, Link2, Palette, Rocket, Settings2, ShieldCheck, Sparkles, Trash2, UserCog, Megaphone, Users, ClipboardCheck } from "lucide-react";

export type PermissionAction = "view" | "create" | "edit" | "delete" | "publish" | "manage";
export type AdminRole = "administrator" | "editor" | "moderator" | "view_only" | "custom";
export interface AdminModule { id:string; number:number; label:string; description:string; icon:LucideIcon; group:"wedding"|"insights"|"management"|"system"; actions:PermissionAction[]; status?:"active"|"planned"; children:{id:string;label:string;description?:string}[]; }

const children=(items:string[])=>items.map(id=>({id,label:id.replaceAll("-"," ")}));
const all:PermissionAction[]=["view","create","edit","delete","publish","manage"];

export const ADMIN_MODULES:AdminModule[]=[
{id:"dashboard",number:1,label:"Dashboard",description:"Website status, pending actions, system health, recent activity, current session and quick actions.",icon:LayoutDashboard,group:"wedding",actions:["view","manage"],children:children(["website-status","pending-actions","system-health","recent-activity","current-session","quick-actions"])},
{id:"website",number:2,label:"Website",description:"Homepage section manager, section ordering and editable public wedding website content.",icon:Globe2,group:"wedding",actions:all,children:children(["section-manager","intro","navigation","home-hero","couple","events-story-memory","gallery-highlights","rsvp","guestbook","footer"])},
{id:"styling",number:3,label:"Styling",description:"Appearance, theme, colours, typography, animations, responsive layouts and loading screen controls.",icon:Palette,group:"wedding",actions:["view","edit","publish","manage"],children:children(["theme","colours","typography","animations","responsive","loading-screen","loading-text","loading-logo","loading-animation","blink-heart","loading-duration"])},
{id:"alerts",number:4,label:"Alerts",description:"Maintenance and announcement status, scheduling, messages and page targeting.",icon:Megaphone,group:"wedding",actions:all,children:children(["maintenance-status","maintenance-message","maintenance-apply-to","announcement-status","announcement-message","announcement-apply-to"])},
{id:"notifications",number:5,label:"Notification / Actions",description:"Notification list and pending, completed and failed administrative actions.",icon:Bell,group:"insights",actions:["view","create","edit","delete","manage"],children:children(["notification-list","pending-actions","completed-actions","failed-actions"])},
{id:"analytics",number:6,label:"Analytics",description:"Website, visitor, page, RSVP and gallery analytics with CSV/PDF export.",icon:BarChart3,group:"insights",actions:["view","manage"],children:children(["overview","visitor-analytics","page-analytics","rsvp-analytics","gallery-analytics","export"])},
{id:"events",number:7,label:"Events / Story Memory",description:"Event list, ordering, visibility, duplication, event details, schedule, location and event security.",icon:CalendarDays,group:"wedding",actions:all,children:children(["event-list","event-details","event-information","schedule","location","gallery","videos","visibility","security"])},
{id:"rsvp",number:8,label:"RSVP",description:"RSVP overview, guest management and configurable RSVP form fields.",icon:ClipboardCheck,group:"wedding",actions:all,children:children(["rsvp-overview","guest-list","guest-management","search-guest","filter-guest","view-guest","add-guest","edit-guest","delete-guest","import-guests","export-guests","form-fields","guest-name","email","phone","attendance","plus-one","meal-preference","dietary-requirements","additional-message","required-optional"])},
{id:"guestbook",number:9,label:"Guestbook",description:"Guestbook message moderation, guest details and moderation settings.",icon:BookOpen,group:"wedding",actions:["view","edit","delete","manage"],children:children(["message-list","pending-approval","approved","rejected","guest-details","moderation"])},
{id:"social",number:10,label:"Social & Contact",description:"Social links, icon visibility and public contact information.",icon:Link2,group:"wedding",actions:["view","edit","publish","manage"],children:children(["social-links","instagram","facebook","youtube","x-twitter","whatsapp","contact-information","contact-form"])},
{id:"media",number:11,label:"Media",description:"Google Drive media source, gallery and QR links, photo/video listing, performance, delivery, guest uploads and privacy.",icon:FileImage,group:"wedding",actions:all,children:children(["media-source","gallery-qr-links","photo-video-listing","image-performance","media-delivery","guest-uploads","media-privacy","private-media-delivery"])},
{id:"interactions",number:12,label:"Interactions",description:"Event unlock, unlock sessions, code storage, protection, guestbook and analytics interaction, favorites, QR and guest uploads.",icon:Heart,group:"wedding",actions:["view","edit","delete","manage"],children:children(["event-unlock","unlock-session","event-code-storage","unlock-protection","guestbook-interaction","analytics-interaction","favorites","qr-interaction","guest-photo-upload"])},
{id:"access",number:13,label:"Access Management",description:"Users, roles and granular permissions.",icon:Users,group:"management",actions:all,children:children(["user-list","add-user","edit-user","disable-user","delete-user","reset-password","role-list","administrator","editor","viewer","permissions","website-permission","styling-permission","rsvp-permission","guestbook-permission","media-permission","analytics-permission","publishing-permission","administration-permission","security-permission"])},
{id:"administration",number:14,label:"Administration",description:"Website information and administrator dashboard preferences.",icon:UserCog,group:"management",actions:all,children:children(["website-details","website-name","website-url","wedding-date","time-zone","language","date-format","dashboard-preferences","default-dashboard-view","default-theme","notification-preferences"])},
{id:"security",number:15,label:"Security",description:"Account security, security alerts and event security center.",icon:ShieldCheck,group:"management",actions:["view","edit","manage"],children:children(["security-settings","change-password","two-factor-authentication","active-sessions","login-history","force-logout-all-sessions","alert-settings","failed-login-alert","new-login-alert","password-change-alert","security-notification-email","event-security","active-events","event-code-status","change-event-code","change-all-event-codes","generate-secure-code","security-status"])},
{id:"audit",number:16,label:"Audit Logs",description:"Searchable administrative activity history with filters, details and export.",icon:FileClock,group:"management",actions:["view","manage"],children:children(["log-list","filter-user","filter-action","filter-date","search-audit-logs","activity-details","export-logs"])},
{id:"publishing",number:17,label:"Publishing",description:"Current publishing status, preview, publish actions, scheduling, unpublish and version history.",icon:Rocket,group:"system",actions:all,children:children(["publishing-status","preview-draft","publish-now","schedule-publish","unpublish","cancel-scheduled-publish","version-history","view-version","compare-version","restore-version"])},
{id:"diagnostics",number:18,label:"Testing & Diagnostics",description:"Website tests, performance, automated testing, application cache, code splitting and diagnostic logs.",icon:Activity,group:"system",actions:["view","manage"],children:children(["website-test","performance","automated-testing","application-cache","code-splitting","diagnostics","run-all-tests","unit-tests","api-tests","authentication-tests","rsvp-tests","guestbook-tests","gallery-tests","guest-upload-tests","test-results","clear-application-cache","update-service-worker","admin-route-loading","gallery-route-loading","video-route-loading","lazy-loaded-components","error-logs","warning-logs","api-errors","integration-errors","run-diagnostics"])},
{id:"integrations",number:19,label:"Integrations",description:"Supabase, Google Drive, GitHub, Vercel and other service integrations.",icon:Boxes,group:"system",actions:all,children:children(["database","supabase","storage","google-drive","source-code","github","deployment","vercel","environment-configuration","environment-variables","api-services","event-unlock-api","guestbook-api","analytics-api","google-drive-api","guest-upload-api","other-integrations"])},
{id:"system",number:20,label:"System",description:"System information and service status for website, database, storage, email, API and cache.",icon:Gauge,group:"system",actions:["view","manage"],children:children(["system-information","application-version","database-version","server-information","environment","time-zone","storage-usage","system-services","website-service","database-service","storage-service","email-service","api-service","cache-service"])},
{id:"backup",number:21,label:"Backup & Restore",description:"Create backups, view history and restore database/content snapshots.",icon:FileArchive,group:"system",actions:["view","create","delete","manage"],children:children(["create-backup","backup-history","restore-backup"])},
{id:"settings",number:22,label:"Settings",description:"General wedding, date/time, language, notification, website and advanced settings.",icon:Settings2,group:"system",actions:["view","edit","manage"],children:children(["general","wedding","date-time","language","notifications","website","advanced"])},
{id:"trash",number:23,label:"Trash & Recovery",description:"Deleted items, recovery settings, restore and permanent deletion.",icon:Trash2,group:"system",actions:["view","delete","manage"],children:children(["deleted-items","events","media","guestbook","content","recovery-settings","restore","permanent-delete"])},
{id:"help",number:24,label:"Help & Support",description:"Documentation, support actions and application information.",icon:HelpCircle,group:"system",actions:["view"],children:children(["documentation","support","support-actions","about","application-information"])}
];

export const ADMIN_ROLES:Record<AdminRole,{label:string;description:string;permissions:Record<string,PermissionAction[]>}>={
 administrator:{label:"Administrator",description:"Full administrative control.",permissions:Object.fromEntries(ADMIN_MODULES.map(m=>[m.id,m.actions]))},
 editor:{label:"Editor",description:"Manage wedding content without security administration.",permissions:Object.fromEntries(ADMIN_MODULES.filter(m=>!["access","administration","security","audit","integrations","system","backup"].includes(m.id)).map(m=>[m.id,m.actions.filter(a=>["view","create","edit","publish"].includes(a))]))},
 moderator:{label:"Moderator",description:"Moderate guest-facing interactions.",permissions:{guestbook:["view","edit","delete","manage"],interactions:["view","delete","manage"],notifications:["view","manage"],rsvp:["view","edit"],dashboard:["view"]}},
 view_only:{label:"View Only",description:"Read-only access.",permissions:Object.fromEntries(ADMIN_MODULES.map(m=>[m.id,["view"]]))},
 custom:{label:"Custom Role",description:"Explicitly assigned permissions.",permissions:{}}
};

export const GROUP_LABELS={wedding:"WEDDING",insights:"INSIGHT",management:"MANAGEMENT",system:"SYSTEM"} as const;
