-- Admin control center: durable drafts, version history, publishing and activity.
create table if not exists public.admin_revisions (
  id uuid primary key default gen_random_uuid(),
  version_no bigint generated by default as identity unique,
  status text not null default 'draft' check (status in ('draft','published','archived')),
  label text not null default 'Admin snapshot',
  snapshot jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  published_at timestamptz
);

create table if not exists public.admin_publish_history (
  id uuid primary key default gen_random_uuid(),
  revision_id uuid not null references public.admin_revisions(id) on delete cascade,
  action text not null check (action in ('publish','rollback')),
  published_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_activity (
  id uuid primary key default gen_random_uuid(),
  admin_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text,
  entity_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_revisions_status_created_idx on public.admin_revisions(status, created_at desc);
create index if not exists admin_publish_history_created_idx on public.admin_publish_history(created_at desc);
create index if not exists admin_activity_created_idx on public.admin_activity(created_at desc);

alter table public.admin_revisions enable row level security;
alter table public.admin_publish_history enable row level security;
alter table public.admin_activity enable row level security;

-- These tables are accessed through the authenticated admin API route using the
-- service role. No direct Data API access is granted to anon/authenticated.
revoke all on public.admin_revisions from anon, authenticated;
revoke all on public.admin_publish_history from anon, authenticated;
revoke all on public.admin_activity from anon, authenticated;

-- Helpful view for the admin API only; service role is used by the server route.
create or replace view public.admin_revision_summary as
select id, version_no, status, label, created_by, created_at, published_at
from public.admin_revisions;

revoke all on public.admin_revision_summary from anon, authenticated;

comment on table public.admin_revisions is 'Durable admin snapshots for draft, publish and rollback workflows.';
comment on table public.admin_publish_history is 'Immutable publish and rollback history.';
comment on table public.admin_activity is 'Server-side admin activity stream.';
